services:
  postgres:
    image: postgres:latest
    container_name: "postgres_container"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: unless-stopped